services:
  - mongodb
language: node_js
node_js:
  - "stable"
  - "0.12"
env:
  - NODE_ENV="development"
  - NODE_ENV="production";SESSION_SECRET="La li lu le lo"
script: gulp travis
notifications:
  email:
    recipients:
      - david.thomas.reeve@gmail.com

